# Generated by Django 6.0.6 on 2026-09-01 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('business', 'Business'), ('product', 'Product')], max_length=50)),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'item_type', 'object_id'], name='bookmarks_s_user_id_ceb735_idx'), models.Index(fields=['user', '-created_at'], name='bookmarks_s_user_id_582caf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'object_id'), name='unique_user_saved_item')],
            },
        ),
    ]
