# Generated by Django 6.0.6 on 2026-09-16 09:05

import catalogs.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('uploads', '0002_remove_upload_height_remove_upload_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=catalogs.models.generate_catalog_public_id, editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('menu', 'Menu Item'), ('property', 'Property'), ('pricing', 'Pricing')], default='menu', max_length=20)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='businesses.business')),
                ('images', models.ManyToManyField(blank=True, related_name='catalogs', to='uploads.upload')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
                'db_table': 'catalogs',
                'ordering': ('name', '-created_at'),
                'indexes': [models.Index(fields=['business', 'type', 'is_active'], name='catalog_business_type_idx'), models.Index(fields=['business', 'is_available', 'is_active'], name='catalog_availability_idx'), models.Index(fields=['type', 'is_active'], name='catalog_type_active_idx')],
            },
        ),
    ]
