# Generated by Django 6.0.6 on 2026-08-31 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('label', models.CharField(blank=True, help_text='Optional public-facing label. Falls back to name when blank.', max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('type', models.CharField(choices=[('product', 'Product'), ('specialty', 'Specialty'), ('property', 'Property'), ('service', 'Service'), ('menu', 'Menu'), ('package', 'Package'), ('other', 'Other')], db_index=True, default='product', max_length=30)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated alternate names/search terms.', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/catalogs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalogs.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_categories',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['type', 'is_active', 'sort_order'], name='catalog_cat_type_active_idx'), models.Index(fields=['type', 'parent', 'is_active'], name='catalog_cat_parent_idx'), models.Index(fields=['type', 'is_featured', 'sort_order'], name='catalog_cat_featured_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'slug'), name='catalog_category_unique_type_slug'), models.UniqueConstraint(fields=('type', 'name'), name='catalog_category_unique_type_name'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='catalog_category_parent_not_self')],
            },
        ),
    ]
