# Generated by Django 6.0.6 on 2026-09-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_catalogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='short_description',
        ),
    ]
