# Generated by Django 6.0.6 on 2026-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_remove_catalog_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='is_display',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
