# Generated by Django 6.0.6 on 2026-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_catalogimageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('doctor', 'Doctor'), ('property', 'Property'), ('menu', 'Menu'), ('package', 'Package'), ('other', 'Other')], db_index=True, default='product', max_length=20),
        ),
    ]
