# Generated by Django 6.0.6 on 2026-09-12 02:43

import businesses.validators
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_businesscategory_parent_and_more'),
        ('locations', '0001_initial'),
        ('uploads', '0002_remove_upload_height_remove_upload_width_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('landmark', models.CharField(blank=True, default='', max_length=200)),
                ('locality', models.CharField(blank=True, default='', max_length=200)),
                ('postal_code', models.CharField(blank=True, db_index=True, default='', max_length=6)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Exact business location (longitude, latitude).', null=True, srid=4326)),
                ('phone', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use international format, such as +919876543210.')])),
                ('whatsapp', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use international format, such as +919876543210.')])),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('display_full_address', models.BooleanField(default=True, help_text='Show street address, landmark, postal code,and exact location publicly.')),
                ('display_business_hours', models.BooleanField(default=True, help_text='Show current open, closing soon, or closed status publicly.')),
                ('is_paid', models.BooleanField(blank=True, default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[businesses.validators.validate_established_year])),
                ('offerings', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='locations.city')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_cover_image', to='uploads.upload')),
                ('gallery', models.ManyToManyField(blank=True, related_name='businesses', to='uploads.upload')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesses',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BusinessCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='businesses.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_assignments', to='categories.businesscategory')),
            ],
            options={
                'db_table': 'business_category_assignments',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='businesses', through='businesses.BusinessCategoryAssignment', to='categories.businesscategory'),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), help_text='Weekdays sharing this slot (Monday=0, Sunday=6).', size=7, validators=[businesses.validators.validate_business_days])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='businesses.business')),
            ],
            options={
                'db_table': 'business_hours',
                'ordering': ('business_id', 'opens_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('social_urls', models.JSONField(blank=True, default=dict, validators=[businesses.validators.validate_social_urls])),
                ('alternate_numbers', models.JSONField(blank=True, default=list, validators=[businesses.validators.validate_alternate_numbers])),
                ('services', models.JSONField(blank=True, default=list)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'Business Profiles',
                'db_table': 'business_profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='businesscategoryassignment',
            constraint=models.UniqueConstraint(fields=('business', 'category'), name='business_category_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='businesscategoryassignment',
            constraint=models.UniqueConstraint(fields=('business', 'sort_order'), name='business_category_sort_order_unique'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['locality', 'status', 'is_active'], name='business_locality_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'is_active', 'published_at'], name='business_publish_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', 'status'], name='business_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshour',
            index=models.Index(fields=['business', 'opens_at'], name='business_hours_open_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['days'], name='business_hours_days_gin'),
        ),
        migrations.AddConstraint(
            model_name='businesshour',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='business_hour_closes_after_open'),
        ),
        migrations.AddConstraint(
            model_name='businesshour',
            constraint=models.UniqueConstraint(fields=('business', 'days', 'opens_at', 'closes_at'), name='business_hour_slot_unique'),
        ),
    ]
