# Generated by Django 6.0.6 on 2026-08-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='business',
            new_name='business_locality_vis_idx',
            old_name='business_locality_visibility_idx',
        ),
    ]
