# Generated by Django 6.0.6 on 2026-08-29 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rename_business_locality_visibility_idx_business_locality_vis_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='handle',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Handle must be 3-50 characters and contain only lowercase letters, numbers, underscores, or hyphens.', regex='^[a-z0-9][a-z0-9_-]{2,49}$')]),
        ),
    ]
