# Generated by Django 6.0.6 on 2026-09-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_businessgalleryupload_kind_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
