# Generated by Django 6.0.6 on 2026-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_business_offerings'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
