# Generated by Django 6.0.6 on 2026-09-16 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('uploads', '0002_remove_upload_height_remove_upload_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_all_time', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='businesses.business')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.upload')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ('sort_order', '-created_at'),
                'indexes': [models.Index(fields=['business', 'is_active'], name='offer_business_active_idx'), models.Index(fields=['business', 'sort_order'], name='offer_business_sort_idx')],
            },
        ),
    ]
