# Generated by Django 6.0.6 on 2026-08-29 04:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, help_text='Plural form of the name.', max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Optional public label; name is used when blank.', max_length=100)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated search terms.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/businesses/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'db_table': 'business_categories',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='business_ca_is_acti_214207_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, help_text='Plural form of the name.', max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Optional public label; name is used when blank.', max_length=100)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated search terms.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='product_category_not_own_parent')],
            },
        ),
    ]
