# Generated by Django 6.0.6 on 2026-08-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='product_category_not_own_parent',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
