# Generated by Django 6.0.6 on 2026-09-12 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.businesscategory'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
