# Generated by Django 6.0.6 on 2026-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_businesscategory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
