# Generated by Django 6.0.6 on 2026-09-15 07:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('uploads', '0002_remove_upload_height_remove_upload_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Singular name, e.g. Cardiologist', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Plural/display label, e.g. Cardiologists', max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated search aliases, e.g. heart doctor, heart specialist', max_length=255)),
                ('body_part', models.CharField(blank=True, choices=[('heart', 'Heart'), ('skin', 'Skin'), ('eye', 'Eye'), ('ent', 'Ear, Nose & Throat'), ('brain_nervous_system', 'Brain & Nervous System'), ('bones_joints', 'Bones & Joints'), ('lungs', 'Lungs'), ('kidney', 'Kidney'), ('digestive_system', 'Stomach & Digestive System'), ('liver', 'Liver'), ('teeth_mouth', 'Teeth & Mouth'), ('womens_health', "Women's Health"), ('child_health', 'Child Health'), ('mental_health', 'Mental Health'), ('hormones_metabolism', 'Hormones & Metabolism'), ('urinary_system', 'Urinary System'), ('reproductive_system', 'Reproductive System'), ('blood', 'Blood'), ('cancer', 'Cancer'), ('general', 'General Health'), ('other', 'Other')], help_text='Primary body part or health system associated with this specialty', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/doctor_specialties/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Doctor Specialty',
                'verbose_name_plural': 'Doctor Specialties',
                'db_table': 'doctorspecialties',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('registration_council', models.CharField(blank=True, max_length=150)),
                ('registration_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list, help_text="Example: ['English', 'Hindi', 'Bengali']")),
                ('treatments', models.JSONField(blank=True, default=list, help_text='Treatments/services commonly provided by the doctor.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='businesses.business')),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.upload')),
                ('specialties', models.ManyToManyField(blank=True, related_name='doctors', to='doctors.doctorspecialty')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly_weekday', 'Monthly Weekday'), ('monthly_date', 'Monthly Date')], db_index=True, max_length=30)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('week_of_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consultation_type', models.CharField(choices=[('walk_in', 'Walk-in'), ('by_appointment', 'By Appointment')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'db_table': 'doctor_schedules',
                'ordering': ['doctor', 'schedule_type', 'weekday', 'week_of_month', 'day_of_month', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'schedule_type', 'is_active'], name='doctor_sche_doctor__15fc0a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='doctor_schedule_end_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active', 'business'], name='doctors_is_acti_d51ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_featured', 'is_active'], name='doctors_is_feat_0045f8_idx'),
        ),
    ]
