# Generated by Django 6.0.6 on 2026-09-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='height',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='width',
        ),
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
