# Generated by Django 6.0.6 on 2026-09-12 04:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Singular category name, e.g. Shirt, Saree, Mobile Phone.', max_length=200)),
                ('label', models.CharField(blank=True, help_text='Plural/public category label, e.g. Shirts, Sarees.', max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Optional shorter public-facing name.', max_length=100)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated alternative search terms.', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['parent', 'is_active', 'sort_order'], name='prodcat_parent_active_idx'), models.Index(fields=['is_featured', 'is_active', 'sort_order'], name='prodcat_featured_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), name='unique_product_category_parent_name'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', True)), name='unique_root_product_category_name')],
            },
        ),
    ]
