# Generated by Django 6.0.6 on 2026-09-12 08:05

import django.core.validators
import django.db.models.deletion
import products.product
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
        ('uploads', '0002_remove_upload_height_remove_upload_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=products.product.generate_product_public_id, editable=False, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Public ID must contain exactly 8 alphanumeric characters.', regex='^[a-z0-9]{8}$')])),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('ask', 'Ask for Price'), ('range', 'Price Range'), ('starts_from', 'Starts From')], db_index=True, default='fixed', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mrp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variants', models.JSONField(blank=True, default=dict, help_text='Product variants.')),
                ('specifications', models.JSONField(blank=True, default=list, help_text='Product specifications.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.productcategory')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='uploads.upload')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductImage', through_fields=('product', 'upload'), to='uploads.upload'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='prod_image_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'upload'), name='unique_product_upload_image'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'status', 'is_available'], name='prod_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_featured', 'sort_order'], name='prod_business_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_available', '-created_at'], name='prod_active_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('mrp_price__isnull', True), ('mrp_price__gte', 0), _connector='OR'), name='product_mrp_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('max_price__isnull', True), ('max_price__gte', 0), _connector='OR'), name='product_max_price_non_negative'),
        ),
    ]
