# Generated by Django 6.0.6 on 2026-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productimage_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_search',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
